server.port=8089
spring.datasource.url=jdbc:mysql://mysql_notification:3306/db_notification?createDatabaseIfNotExist=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true