server.port=8087
spring.datasource.url=jdbc:mysql://mysql_search:3306/db_search?createDatabaseIfNotExist=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true