server.port=8088
spring.datasource.url=jdbc:mysql://mysql_fine:3306/db_fine?createDatabaseIfNotExist=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true